'use client'

import { useState, useEffect } from 'react'
import { taskService } from '@/lib/supabase/services/index'
import { isSupabaseConfigured } from '@/lib/supabase/client'
import { Button } from '@/components/ui/button'
import { useToast } from '@/components/ui/toast-provider'
import { AlertCircle, CalendarIcon, TrendingUp, Target, CheckCircle, Plus, BarChart3 } from 'lucide-react'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { format, addDays, subDays, startOfWeek, endOfWeek, startOfMonth, endOfMonth } from 'date-fns'
import { zhCN } from 'date-fns/locale'
import { useAuth } from '@/lib/auth/useAuth'
import { Task } from '@/types/database'
import { LoadingError } from '@/components/ui/loading-error'
import { TaskFilters } from '@/components/tasks/task-filters'
import { TaskList } from '@/components/tasks/task-list'
import { TaskCalendar } from '@/components/tasks/task-calendar'
import { TaskStats } from '@/components/tasks/task-stats'
import { TaskForm } from '@/components/tasks/task-form'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
